return {

  -- {
  --   "nvim-lualine/lualine.nvim",
  --   event = "VeryLazy",
  --   opts = function()
  --     -- local git_blame = require("gitblame")
  --     return {
  --
  --       require("lualine").setup({
  --         options = {
  --           icons_enabled = true,
  --           theme = "catppuccin",
  --           component_separators = {
  --             left = "",
  --             right = "",
  --           },
  --           section_separators = {
  --             left = "",
  --             right = "",
  --           },
  --           disabled_filetypes = {
  --             statusline = {},
  --             winbar = {},
  --           },
  --           ignore_focus = {},
  --           always_divide_middle = true,
  --           globalstatus = false,
  --           refresh = {
  --             statusline = 1000,
  --             tabline = 1000,
  --             winbar = 1000,
  --           },
  --         },
  --         sections = {
  --           lualine_a = { "mode" },
  --           lualine_b = { "branch", "diff", "diagnostics" },
  --           lualine_c = {
  --             {
  --               color = {
  --                 fg = "#1e1e2e",
  --                 bg = "#1e1e2e",
  --               },
  --             },
  --           },
  --           lualine_x = {
  --             {
  --               git_blame.get_current_blame_text,
  --               cond = git_blame.is_blame_text_available,
  --               draw_empty = false,
  --               separator = {
  --                 right = "",
  --                 left = "",
  --               },
  --               color = {
  --                 fg = "#282A36",
  --                 bg = "#eba0ac",
  --               },
  --             },
  --           },
  --           lualine_y = { "progress" },
  --           lualine_z = { "location" },
  --         },
  --         inactive_sections = {
  --           lualine_a = {},
  --           lualine_b = {},
  --           lualine_c = { "filename" },
  --           lualine_x = { "location" },
  --           lualine_y = {},
  --           lualine_z = {},
  --         },
  --         tabline = {},
  --         winbar = {},
  --         inactive_winbar = {},
  --         extensions = {},
  --       }),
  --     }
  --   end,
  -- },
}
